add regenerate of pydantic model to GH action

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -53,5 +53,17 @@ jobs:
       - name: Install dependencies
         run: uv sync
 
-      - name: Run test suite
-        run: make test
+      - name: Generate LinkML-Map Transformation Model artifacts
+        run: |
+          make src/linkml_map/datamodel/transformer_model.py
+          make test
+          if [ $? -eq 0 ]; then
+            git config --local user.email "action@github.com"
+            git config --local user.name "GitHub Action"
+            git add project/*
+            git add src/*
+            git commit -m "Regenerate artifacts from linkml-map transformer_model.yaml"
+            git push
+          else
+            echo "'make' gen-project failed to finish successfully"
+          fi
